// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id          int64  `json:"id"`
	UserAccount string `json:"userAccount"`
	UserName    string `json:"userName"`
	UserAvatar  string `json:"userAvatar"`
	UserProfile string `json:"userProfile"`
	UserRole    string `json:"userRole"`
	CreateTime  string `json:"createTime"`
	UpdateTime  string `json:"updateTime"`
}

type UserResponse struct {
	Id          int64  `json:"id"`
	UserAccount string `json:"userAccount"`
	UserName    string `json:"userName"`
	UserAvatar  string `json:"userAvatar"`
	UserProfile string `json:"userProfile"`
	UserRole    string `json:"userRole"`
	CreateTime  string `json:"createTime"`
	UpdateTime  string `json:"updateTime"`
}

type LoginUserResponse struct {
	Id          int64  `json:"id"`
	UserAccount string `json:"userAccount"`
	UserName    string `json:"userName"`
	UserAvatar  string `json:"userAvatar"`
	UserProfile string `json:"userProfile"`
	UserRole    string `json:"userRole"`
	CreateTime  string `json:"createTime"`
	UpdateTime  string `json:"updateTime"`
	Token       string `json:"token"`
}

type UserRegisterRequest struct {
	UserAccount   string `json:"userAccount"`
	UserPassword  string `json:"userPassword"`
	CheckPassword string `json:"checkPassword"`
}

type UserLoginRequest struct {
	UserAccount  string `json:"userAccount"`
	UserPassword string `json:"userPassword"`
}

type UserAddRequest struct {
	UserName    string `json:"userName,optional"`
	UserAccount string `json:"userAccount"`
	UserAvatar  string `json:"userAvatar,optional"`
	UserProfile string `json:"userProfile,optional"`
	UserRole    string `json:"userRole"`
}

type UserUpdateRequest struct {
	Id          int64  `path:"id"`
	UserName    string `json:"userName,optional"`
	UserAvatar  string `json:"userAvatar,optional"`
	UserProfile string `json:"userProfile,optional"`
	UserRole    string `json:"userRole,optional"`
}

type UserQueryRequest struct {
	Current     int64  `form:"current,default=1"`
	PageSize    int64  `form:"pageSize,default=10"`
	SortField   string `form:"sortField,optional"`
	SortOrder   string `form:"sortOrder,optional"`
	Id          int64  `form:"id,optional"`
	UnionId     string `form:"unionId,optional"`
	MpOpenId    string `form:"mpOpenId,optional"`
	UserName    string `form:"userName,optional"`
	UserProfile string `form:"userProfile,optional"`
	UserRole    string `form:"userRole,optional"`
}

type IdPathRequest struct {
	Id int64 `path:"id"`
}

type IdRequest struct {
	Id int64 `json:"id"`
}

type BaseResponseLong struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data int64  `json:"data"`
}

type BaseResponseBoolean struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data bool   `json:"data"`
}

type BaseResponseString struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data string `json:"data"`
}

type BaseResponseLoginUserResponse struct {
	Code int               `json:"code"`
	Msg  string            `json:"msg"`
	Data LoginUserResponse `json:"data"`
}

type BaseResponseUserResponse struct {
	Code int          `json:"code"`
	Msg  string       `json:"msg"`
	Data UserResponse `json:"data"`
}

type BaseResponseUser struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data User   `json:"data"`
}

type UserPage struct {
	Records []UserResponse `json:"records"`
	Total   int64          `json:"total"`
}

type BaseResponseUserPage struct {
	Code int      `json:"code"`
	Msg  string   `json:"msg"`
	Data UserPage `json:"data"`
}
