// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	system "github.com/YuanJun-93/CodeGenesis/internal/handler/system"
	"github.com/YuanJun-93/CodeGenesis/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/healthz",
				Handler: system.HealthzHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
