// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userFieldNames          = builder.RawFieldNames(&User{})
	userRows                = strings.Join(userFieldNames, ",")
	userRowsExpectAutoSet   = strings.Join(stringx.Remove(userFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userRowsWithPlaceHolder = strings.Join(stringx.Remove(userFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	UserModel interface {
		Insert(ctx context.Context, data *User) error
		FindOne(ctx context.Context, id int64) (*User, error)
		FindOneByUserAccount(ctx context.Context, userAccount string) (*User, error)
		Update(ctx context.Context, data *User) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	User struct {
		Id           int64          `db:"id"`           // ID
		UserAccount  string         `db:"userAccount"`  // User Account
		UserPassword string         `db:"userPassword"` // User Password
		UserName     sql.NullString `db:"userName"`     // User Name
		UserAvatar   sql.NullString `db:"userAvatar"`   // User Avatar
		UserProfile  sql.NullString `db:"userProfile"`  // User Profile
		UserRole     string         `db:"userRole"`     // User Role: user/admin
		EditTime     time.Time      `db:"editTime"`     // Edit Time
		CreateTime   time.Time      `db:"createTime"`   // Create Time
		UpdateTime   time.Time      `db:"updateTime"`   // Update Time
		IsDelete     int64          `db:"isDelete"`     // Is Deleted
	}
)

func newUserModel(conn sqlx.SqlConn) *defaultUserModel {
	return &defaultUserModel{
		conn:  conn,
		table: "`user`",
	}
}

func (m *defaultUserModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserModel) FindOne(ctx context.Context, id int64) (*User, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRows, m.table)
	var resp User
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) FindOneByUserAccount(ctx context.Context, userAccount string) (*User, error) {
	var resp User
	query := fmt.Sprintf("select %s from %s where `userAccount` = ? limit 1", userRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userAccount)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) Insert(ctx context.Context, data *User) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserAccount, data.UserPassword, data.UserName, data.UserAvatar, data.UserProfile, data.UserRole, data.EditTime, data.CreateTime, data.UpdateTime, data.IsDelete)
	return ret, err
}

func (m *defaultUserModel) Update(ctx context.Context, newData *User) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserAccount, newData.UserPassword, newData.UserName, newData.UserAvatar, newData.UserProfile, newData.UserRole, newData.EditTime, newData.CreateTime, newData.UpdateTime, newData.IsDelete, newData.Id)
	return err
}

func (m *defaultUserModel) tableName() string {
	return m.table
}
