// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User User
type User struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`                               // id
	UserAccount  string    `gorm:"column:userAccount;not null;comment:User Account" json:"userAccount"`                        // User Account
	UserPassword string    `gorm:"column:userPassword;not null;comment:Password" json:"userPassword"`                          // Password
	UserName     string    `gorm:"column:userName;comment:User Name" json:"userName"`                                          // User Name
	UserAvatar   string    `gorm:"column:userAvatar;comment:User Avatar" json:"userAvatar"`                                    // User Avatar
	UserProfile  string    `gorm:"column:userProfile;comment:User Profile" json:"userProfile"`                                 // User Profile
	UserRole     string    `gorm:"column:userRole;not null;default:user;comment:User Role: user/admin" json:"userRole"`        // User Role: user/admin
	EditTime     time.Time `gorm:"column:editTime;not null;default:CURRENT_TIMESTAMP;comment:Edit Time" json:"editTime"`       // Edit Time
	CreateTime   time.Time `gorm:"column:createTime;not null;default:CURRENT_TIMESTAMP;comment:Create Time" json:"createTime"` // Create Time
	UpdateTime   time.Time `gorm:"column:updateTime;not null;default:CURRENT_TIMESTAMP;comment:Update Time" json:"updateTime"` // Update Time
	IsDelete     int32     `gorm:"column:isDelete;not null;comment:Is Deleted" json:"isDelete"`                                // Is Deleted
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
